apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: danielpinhas/flask-k8s
        ports:
        - containerPort: 5000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-url

---

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30100
