pipeline {
    agent any

    environment {
        // Initialize the initial version tag
        IPtest = '172.31.240.22'
    }

    stages {
        stage('Clean Up & Clone') {
            steps {
                sh 'sudo rm -rf *'
                sh 'git clone https://github.com/Daniel-Pinhas/DevOps-Projects.git'
                echo 'Clean Up & Clone Stage Completed'
            }
        }

        stage('Build and Push Flask-1 Image') {
            steps {
                dir('DevOps-Projects/Pipeline-EKS/Flask-Project/') {
                    sh '''
                    chmod +x manageVersion.py
                    python3 manageVersion.py
                    '''
                }
                echo 'Build and Push Flask-1 Image Stage Completed'
            }
        }

        stage('Build and Push Flask-2 Image') {
            steps {
                dir('DevOps-Projects/Pipeline-EKS/Flask-Project2/') {
                    sh '''
                    chmod +x manageVersion.py
                    python3 manageVersion.py
                    '''
                }
                echo 'Build and Push Flask-2 Image Stage Completed'
            }
        }

        stage('Build and Push Flask-3 Image') {
            steps {
                dir('DevOps-Projects/Pipeline-EKS/Flask-Project3/') {
                    sh '''
                    chmod +x manageVersion.py
                    python3 manageVersion.py
                    '''
                }
                echo 'Build and Push Flask-3 Image Stage Completed'
            }
        }       

        stage('Deploy to Test Env: Rancher Desktop') {
            steps {                
                dir('DevOps-Projects/Pipeline-EKS/K8S-YAML/') {
                    sh '''
                    kubectl config use-context rancher-desktop  
                    kubectl apply -f /var/lib/jenkins/.ssh/rds.yml
                    kubectl apply -f html-configmap.yml
                    kubectl apply -f httpd-deployment.yml
                    cd ../flask-charts && python3 changeTagValues.py
                    cd ../flask-charts && helm upgrade --install flask-app . --values values.yml
                    '''
                }
                echo 'Deploy Application into Rancher Desktop Completed'
            }
        }
    
        stage('Testing Test-Server') {
            steps {
                dir('DevOps-Projects/Pipeline-K8S/tests/') {
                sh 'bash test.sh'
                }
            }
        }


        stage('Deploy to Production Env: GCP Cluster') {
            steps {                
                dir('DevOps-Projects/Pipeline-EKS/K8S-YAML/') {
                    sh '''
                    kubectl config use-context gke_lofty-dynamics-393510_us-central1-a_gifs-website
                    kubectl apply -f html-configmap.yml
                    kubectl apply -f httpd-deployment.yml
                    cd ../flask-charts && helm upgrade --install flask-app . --values values.yml
                    '''
                }
                echo 'Deploy Application into Rancher Desktop Completed'
            }   
        }

        stage('Testing Test-Server') {
            steps {
                dir('DevOps-Projects/Pipeline-K8S/tests/') {
                sh 'bash test.sh'
                }
            }
        }
    }
}

