---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-flask1
spec:
  type: NodePort
  selector:
    app: flask-1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: {{ .Values.flask1.nodePort }}

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-flask2
spec:
  type: NodePort
  selector:
    app: flask-2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: {{ .Values.flask2.nodePort }}

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-flask3
spec:
  type: NodePort
  selector:
    app: flask-3
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: {{ .Values.flask3.nodePort }}