apiVersion: v1
kind: Service
metadata:
  name: flask-service-{{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: flask-{{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: {{ index .Values (printf "node_port_flask%s" .Release.Name) }}
