apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"index-service","namespace":"default"}}
  creationTimestamp: "2023-07-07T12:12:38Z"
  name: flask-service2
  namespace: default
  resourceVersion: "10312"
  uid: 8f15565a-14af-4d16-ac2e-b3c04dbcdd20
spec:
  clusterIP: 10.98.82.48
  clusterIPs:
  - 10.98.82.48
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 30100
  selector:
    app: index
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
