pipeline {
    agent any

    environment {
        // Initialize the initial version tag
        flask1 = 'flask-k8s'
        flask2 = 'flask2-k8s'
        flask3 = 'flask3-k8s'
        dockerHubUsername = 'danielpinhas'
        IPtest = '172.21.251.200'
    }

    stages {
        stage('Clean Up & Clone') {
            steps {
                sh 'sudo rm -rf *'
                sh 'git clone https://github.com/Daniel-Pinhas/DevOps-Projects.git'
                echo 'Clean Up & Clone Stage Completed'
            }
        }

        stage('Build and Push Flask-1 Image') {
            steps {
                dir('DevOps-Projects/Pipeline-K8S/Flask-Project/') {
                    sh '''
                    chmod +x manageVersion.py
                    python3 manageVersion.py
                    '''
                }
                echo 'Build and Push Flask-1 Image Stage Completed'
            }
        }

        stage('Build and Push Flask-2 Image') {
            steps {
                dir('DevOps-Projects/Pipeline-K8S/Flask-Project2/') {
                    sh '''
                    chmod +x manageVersion.py
                    python3 manageVersion.py
                    '''
                }
                echo 'Build and Push Flask-2 Image Stage Completed'
            }
        }

        stage('Build and Push Flask-3 Image') {
            steps {
                dir('DevOps-Projects/Pipeline-K8S/Flask-Project3/') {
                    sh '''
                    chmod +x manageVersion.py
                    python3 manageVersion.py
                    '''
                }
                echo 'Build and Push Flask-3 Image Stage Completed'
            }
        }       

        stage('Deploy Application into Rancher Desktop') {
            steps {                
                dir('DevOps-Projects/Pipeline-K8S/K8S-YAML/') {
                    sh '''
                    kubectl delete deployment --all
                    kubectl delete service --all
                    kubectl apply -f mysql.yml
                    kubectl apply -f flask.yml
                    kubectl apply -f html-configmap.yml
                    kubectl apply -f httpd-deployment.yml
                    '''
                }
                echo 'Deploy Application into Rancher Desktop Completed'
            }
        }
    
        stage('Testing Test-Server') {
            steps {
                dir('DevOps-Projects/Pipeline-K8S/tests/') {
                sh 'bash test.sh'

                }
            }
        }
    }
}

