version: '3'
services:
  app:
    image: danielpinhas/flask-compose  # Path to your Flask project's Dockerfile
    links:
      - db
    ports:
      - 5000:5000  # Expose Flask application on port 5000
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devopsroles
      - MYSQL_USER=daniel
      - MYSQL_PASSWORD=daniel
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro  # Mount a directory with SQL scripts

