pipeline {
    agent any

    environment {
        // Initialize the initial version tag
        repositoryName = 'flask-compose'
        dockerHubUsername = 'danielpinhas'
        IPtest = '3.138.126.216'
        IPprod = '3.137.190.184'
    }

    stages {
        stage('Clean Up & Clone') {
            steps {
                sh 'sudo rm -rf *'
                sh 'git clone https://github.com/Daniel-Pinhas/DevOps-Projects.git'
                echo 'Clean Up & Clone Stage Completed'
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                dir('DevOps-Projects/Pipeline-Docker-Compose/Flask-Project/') {
                    sh '''
                    chmod +x manageVersion.py
                    python3 manageVersion.py
                    '''
                }
                echo 'Build and Push Docker Image Stage Completed'
            }
        }


        stage('Copy Pipeline to Test-EC2') {
            steps {
                  withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWS Credential 1']]) {
                    sh "scp -i /var/lib/jenkins/.ssh/key.pem /var/lib/jenkins/workspace/Pipeline-Docker-Compose/DevOps-Projects/Pipeline-Docker-Compose/docker-compose.yml ec2-user@${IPtest}:~"
                }
                echo 'Copy Pipeline to Test-EC2 Stage Completed'
            }
        }       

        stage('Deploy Docker into EC2 Test-Servers') {
            steps {                
                script {
                    def sshCommand = "ssh -i /var/lib/jenkins/.ssh/key.pem -o StrictHostKeyChecking=no ec2-user@${IPtest}"
                    sh """
                        ${sshCommand} sudo yum update -y
                        ${sshCommand} sudo yum install docker -y
                        ${sshCommand} sudo service docker start
                        ${sshCommand} sudo systemctl start docker
                        ${sshCommand} sudo curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-`uname -s`-`uname -m` | sudo tee /usr/local/bin/docker-compose > /dev/null
                        ${sshCommand} sudo chmod +x /usr/local/bin/docker-compose
                        if ${sshCommand} sudo lsof -Pi :5000 -sTCP:LISTEN -t >/dev/null; then
                            ${sshCommand} cd Pipeline-Docker-Compose && sudo docker-compose down && ${sshCommand} cd Pipeline-Docker-Compose && sudo docker-compose up
                        else
                            ${sshCommand} cd Pipeline-Docker-Compose && sudo docker-compose up
                        fi
                    """
                }
            }
        }
    
        stage('Testing Test-Server') {
            steps {
                dir('DevOps-Projects/Pipeline-Docker-Compose/tests/') {
                sh 'bash test.sh'
            }
        }
    }

        stage('Copy Pipeline to Prod-EC2') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWS Credential 1']]) {
                    sh "sudo scp -r -i /var/lib/jenkins/.ssh/key.pem /var/lib/jenkins/workspace/Pipeline-Docker-Compose/DevOps-Projects/Pipeline-Docker-Compose/docker-compose.yml ec2-user@${IPprod}:~"
                    sh "sudo scp -r -i /var/lib/jenkins/.ssh/key.pem /var/lib/jenkins/workspace/Pipeline-Docker-Compose/DevOps-Projects/Pipeline-Docker-Compose/db/init.sql ec2-user@${IPprod}:~"
                    sh "sudo scp -r -i /var/lib/jenkins/.ssh/key.pem /var/lib/jenkins/workspace/Pipeline-Docker-Compose/DevOps-Projects/Pipeline-Docker-Compose/Flask-Project/Dockerfile ec2-user@${IPprod}:~"
                }
                echo 'Copy Pipeline to Prod-EC2 Stage Completed'
            }
        }



        stage('Deploy Docker into EC2 Prod-Servers') {
            steps {
                script {
                    def sshCommand = "ssh -i /var/lib/jenkins/.ssh/key.pem -o StrictHostKeyChecking=no ec2-user@${IPtest}"
                    sh """
                        ${sshCommand} sudo yum update -y
                        ${sshCommand} sudo yum install docker -y
                        ${sshCommand} sudo service docker start
                        ${sshCommand} sudo systemctl start docker
                        ${sshCommand} sudo curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-`uname -s`-`uname -m` | sudo tee /usr/local/bin/docker-compose > /dev/null
                        ${sshCommand} sudo chmod +x /usr/local/bin/docker-compose
                        if ${sshCommand} sudo lsof -Pi :5000 -sTCP:LISTEN -t >/dev/null; then
                            ${sshCommand} sudo docker-compose down && ${sshCommand} sudo docker-compose up
                        else
                            ${sshCommand} sudo docker-compose up
                        fi
                    """
                }
            }
        }

        stage('Testing Prod-Server') {
            steps {
                dir('DevOps-Projects/Pipeline-Docker-Compose/tests/') {
                sh 'bash prod.sh'
                }
            }
        }
    }
}