pipeline {
    agent any

    environment {
        // Initialize the initial version tag
        repositoryName = 'flask-compose'
        dockerHubUsername = 'danielpinhas'
        IPtest = '18.117.152.236'
        IPprod = '3.136.26.42'
    }

    stages {
        stage('Clean Up & Clone') {
            steps {
                sh 'sudo rm -rf *'
                sh 'git clone https://github.com/Daniel-Pinhas/DevOps-Projects.git'
                echo 'Clean Up & Clone Stage Completed'
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                dir('DevOps-Projects/Pipeline-Docker-Compose/Flask-Project/') {
                    sh '''
                    chmod +x manageVersion.py
                    python3 manageVersion.py
                    '''
                }
                echo 'Build and Push Docker Image Stage Completed'
            }
        }

        stage('Deploy Docker into EC2 Test-Servers') {
            steps {
                
                script {
                    def sshCommand = "ssh -i /var/lib/jenkins/.ssh/dan.pem -o StrictHostKeyChecking=no ec2-user@${IPtest}"
                    sh """
                        ${sshCommand} sudo yum update -y
                        ${sshCommand} sudo yum install docker -y
                        ${sshCommand} sudo rm -rf Pipeline-Docker-Compose
                        sudo scp -r -i /var/lib/jenkins/.ssh/dan.pem -o StrictHostKeyChecking=no /var/lib/jenkins/workspace/Pipeline-Docker-Compose/DevOps-Projects/Pipeline-Docker-Compose ec2-user@${IPtest}:/home/ec2-user
                        ${sshCommand} sudo lsof -Pi :5000 -sTCP:LISTEN -t >/dev/null && cd Pipeline-Docker-Compose && sudo docker-compose down || ${sshCommand} cd Pipeline-Docker-Compose && sudo docker-compose up
                    """
                }
            }
        }
    
        stage('Testing Test-Server') {
            steps {
                dir('DevOps-Projects/Pipeline-Docker-Compose/tests/') {
                sh 'bash test.sh'
            }
        }
    }
        stage('Deploy Docker into EC2 Prod-Servers') {
            steps {
                script {
                    def sshCommand = "ssh -i /var/lib/jenkins/.ssh/dan.pem -o StrictHostKeyChecking=no ec2-user@${IPtest}"
                    sh """
                        sudo scp -i /var/lib/jenkins/.ssh/dan.pem /var/lib/jenkins/workspace/Pipeline-Docker-Compose/DevOps-Projects/Pipeline-Docker-Compose ec2-user@${IPtest}:~
                        ${sshCommand} sudo yum update -y
                        ${sshCommand} sudo yum install docker -y
                        ${sshCommand} sudo service docker start
                        ${sshCommand} sudo systemctl start docker 
                        ${sshCommand} sudo lsof -Pi :5000 -sTCP:LISTEN -t >/dev/null && sudo docker-compose down || (${sshCommand} docker-compose up)
                    """
                }
            }
        }

        stage('Testing Prod-Server') {
            steps {
                dir('DevOps-Projects/Pipeline-Docker-Compose/tests/') {
                sh 'bash prod.sh'
                }
            }
        }
    }
}
