---
- hosts: all
  become: true
  tasks:
    - name: Install Python and pip
      dnf:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Flask
      pip:
        name: flask
        state: present

    - name: Install Gunicorn
      pip:
        name: gunicorn
        state: present

    - name: Create Flask systemd service
      template:
        src: /var/lib/jenkins/workspace/Pipeline-S3/DevOps-Projects/Pipeline-S3/Ansilbe/templates/flask.service.j2
        dest: /etc/systemd/system/flaskapp.service

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Start Flask App service
      command: systemctl start flaskapp.service

    - name: Enable Flask App service on boot
      command: systemctl enable flaskapp.service
